from .normalize_position import normalize_position
from .find_name_law import find_name_and_law
from .get_units_list import get_units_list
from .find_job_location_position import find_job_location_position